### ISSUE TITLE
Kafka issue

### ISSUE THREAD

**Issue by sivavek** [iam-veeramalla/ultimate-devops-project-aws#7]
The Kafka service fail to start and hence the e-commerce app is not up and unable to access at port 8080. I'm getting the below error message when i run the 'docker compose up' command;

```
kafka            | OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended [otel.javaagent 2025-06-25 18:44:22:621 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.16.0 [otel.javaagent 2025-06-25 18:44:25:807 +0000] [main] INFO io.opentelemetry.javaagent.shaded.instrumentation.jmx.yaml.RuleParser - kafka-broker: found 20 metric rules Exception in thread "main" org.apache.kafka.common.config.ConfigException: If using process.roles, either controller.quorum.bootstrap.servers must contain the set of bootstrap controllers or controller.quorum.voters must contain a parseable set of controllers. at kafka.server.KafkaConfig.validateQuorumVotersAndQuorumBootstrapServerForKRaft$1(KafkaConfig.scala:917) at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:991) at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:867) at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:184) at kafka.tools.StorageTool$.$anonfun$execute$1(StorageTool.scala:79) at scala.Option.flatMap(Option.scala:283) at kafka.tools.StorageTool$.execute(StorageTool.scala:79) at kafka.tools.StorageTool$.main(StorageTool.scala:46) at kafka.docker.KafkaDockerWrapper$.main(KafkaDockerWrapper.scala:48) at kafka.docker.KafkaDockerWrapper.main(KafkaDockerWrapper.scala)
kafka exited with code 1
**dependency failed to start: container kafka is unhealthy**
```

Please help with fixing the issue. I'm stuck and unable to complete the project.

TIA

**Comment by theradheshyampatil** [comment]
The error you're encountering is due to incorrect Kafka configuration, particularly with the controller settings when using KRaft mode (which is Kafka's Zookeeper-less mode). Here's how to fix it:

### Step 1: Check Kafka Configuration

In KRaft mode, if you're using `process.roles`, you need to specify one of the following settings:

* `controller.quorum.bootstrap.servers`: This should list the bootstrap servers for the Kafka controller.
* `controller.quorum.voters`: This should list the Kafka controller voters.

### Step 2: Fix Kafka Configurations

#### Option 1: If Using KRaft Mode (Zookeeper-less Kafka)

If you're using KRaft mode, update your `server.properties` or Docker Compose environment variables with the following configuration:

```properties
process.roles=broker,controller
controller.quorum.bootstrap.servers=localhost:9092
controller.quorum.voters=localhost:9093
```

Ensure that the ports (`9092` and `9093`) match your Kafka container's configuration.

#### Option 2: If Using Zookeeper (Not KRaft Mode)

If you're still using Zookeeper with Kafka, make sure the `bootstrap.servers` setting points to the correct Zookeeper service. The setting should look like this:

```properties
bootstrap.servers=zookeeper:2181
```

### Step 3: Update Docker Compose File

In your `docker-compose.yml` file, ensure that the Kafka service has the correct environment variables. If you're using KRaft mode, include the `controller.quorum.bootstrap.servers` and `controller.quorum.voters` settings in the environment section.

Here's a basic example for Kafka with Zookeeper:

```yaml
version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
```

If you're using KRaft mode, make sure to add the `controller.quorum.bootstrap.servers` and `controller.quorum.voters` settings.

### Step 4: Add a Health Check for Kafka

To ensure Kafka starts properly and Docker doesn't mark it as unhealthy, you can add a health check in your Docker Compose file. Here's an example:

```yaml
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 10s
```

This will check if Kafka is accessible on port `9092`.

### Step 5: Restart Kafka and Docker Compose

After making the changes, restart your Kafka and Docker containers to apply the new configuration. You can do this by running:

```bash
docker-compose down
docker-compose up --build
```

This will rebuild the containers and should start the Kafka service properly, allowing your e-commerce app to access port `8080`.
